### ISSUE TITLE
Renaming a component created from bodies fails

### ISSUE THREAD

**Issue by tg73** [thomasa88/ParametricText#17]
Even in a design with no parametric text configured:
1. Create a component from one or more bodies
2. Rename the component -> ParametricText complains

I'm using PT version 2.0.0.

```
---------------------------
Fusion 360
---------------------------
ParametricText v 2.0.0 error: 5 : Body->Comp1 / 1 Reference Failures The body reference is lost, try editing this feature to reselect the lost body. // Body 1 missing / Compute Failed // No valid source Body found, cache will be used
RemoveBody-Body1(Body->Comp1) / 1 Reference Failures The body reference is lost, try editing this feature to reselect the lost body. // Body 1 missing / Compute Failed // The target body is lost, try editing this feature to reselect target body.

Copy this message using Ctrl+C (Windows) or take a screenshot (Mac). Describe what you did to get this error or record a video.

--------------------------------------------------

AddIns\ParametricText\thomasa88lib\events.py failed: 

Traceback (most recent call last):
  File "/ParametricText\thomasa88lib\events.py", line 142, in catcher
    func(args)
  File "/ParametricText/ParametricText.py", line 1109, in update_cmd_execute_handler
    update_texts(*async_update_queue_.get())
  File "/ParametricText/ParametricText.py", line 1088, in update_texts
    design.computeAll()
  File "/packages\adsk\fusion.py", line 15904, in computeAll
    return _fusion.Design_computeAll(self)
RuntimeError: 5 : Body->Comp1 / 1 Reference Failures The body reference is lost, try editing this feature to reselect the lost body. // Body 1 missing / Compute Failed // No valid source Body found, cache will be used
RemoveBody-Body1(Body->Comp1) / 1 Reference Failures The body reference is lost, try editing this feature to reselect the lost body. // Body 1 missing / Compute Failed // The target body is lost, try editing this feature to reselect target body.

---------------------------
OK   
---------------------------
```

**Comment by tg73** [comment]
Actually, I think this was collateral damage from a Fusion bug. Closing.

**Comment by thomasa88** [comment]
Some more info: ParametricText runs "Compute All" to force features to refresh (if that option is selected). The error from the Compute All is then given to ParametricText, instead of showing as a notification in the lower left of Fusion's window. ParametricText currently has no handling of the error and shows a generic error dialog. Issue: #9 

Also, since version 2.1 (released today), Compute All will only be run when there are update texts in a document, so a ParametricText will no longer run unnecessary Compute All calls for documents without any parametric texts. #16
