### ISSUE TITLE
"InternalValidationError : dataFile error" when opening document before opening its folder or opening document from Editable Files

### ISSUE THREAD

**Issue by thomasa88** [thomasa88/ParametricText#22]
"RuntimeError: 2 : InternalValidationError : dataFile" occurs when opening a document before opening its folder. This reportedly happens in all cases: https://forums.autodesk.com/t5/fusion-360-api-and-scripts/error-retrieving-datafile-in-unopened-folder/m-p/8384143#M6854

But more specifically:
1. Start Fusion 360
2. Click on "x of 10" on the top right
3. Click My editable documents
4. Open a file from the "My editable documents" "folder"
5. Add-ins cannot get the datafile for that document (InternalValidationError)

```
---------------------------
Fusion 360
---------------------------
ParametricText v 2.1.0 error: 2 : InternalValidationError : dataFile

Copy this message using Ctrl+C (Windows) or take a screenshot (Mac). Describe what you did to get this error or record a video.

--------------------------------------------------

H:\my_src\fusion360\ParametricText\thomasa88lib\events.py failed: 

Traceback (most recent call last):
  File "H:/my_src/fusion360/ParametricText\thomasa88lib\events.py", line 142, in catcher
    func(args)
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 273, in map_cmd_created_handler
    add_insert_button(table_input, InsertButtonValue('{_.version}'), 'Append the document version parameter.')
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 323, in add_insert_button
    tooltip += '<br><br>Current value: ' + evaluate_text(insert_value.value, None)
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 833, in evaluate_text
    shown_text = SUBST_PATTERN.sub(sub_func, text)
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 739, in sub_func
    version = app_.activeDocument.dataFile.versionNumber
  File "/packages\adsk\core.py", line 8505, in _get_dataFile
    return _core.Document__get_dataFile(self)
RuntimeError: 2 : InternalValidationError : dataFile

---------------------------
OK   
---------------------------

```

**Comment by thomasa88** [comment]
Try the workaround in the Fusion 360 forum thread.

**Comment by thomasa88** [comment]
For current editable documents:
```

if app.data.personalUseLimits:
files=app.data.personalUseLimits.editableFiles  # This is enough to cache the data
```

**Comment by thomasa88** [comment]
Logic should fetch the "editable documents" first (quicker) and, if that does not get use the dataFile, fetch all:
```
        for p in app_.data.dataProjects:
            root = p.rootFolder
            # check folders as well!
            for df in root.dataFiles:
                df.id
        print("DATAFILE:", app_.activeDocument.dataFile)
```

And of course, only when app_.activeDocument.isSaved.
