### ISSUE TITLE
Text disappears when updated by ParametricText

### ISSUE THREAD

**Issue by thomasa88** [thomasa88/ParametricText#24]
**Describe the bug**
Text parameter disappears when ParametricText updates it. The sketch is there but the text seems to have zero size.

**To Reproduce**
1. Open attached file
2. Make the parametric text update: change value or save to make a new version
3. The version text inside the cap disappears.

**Expected behavior**
Text should update the value. Size should remain the same.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/89997/121574865-fb61f100-ca26-11eb-88af-475e241984cd.png)
After:
![image](https://user-images.githubusercontent.com/89997/121574921-0b79d080-ca27-11eb-8bc1-fb190751a843.png)

**Software**
 - OS: Windows
 - Fusion 360 version: 2.0.10253 (and the previous one)
 - ParametricText version: v. 2.2.0-beta.1

[negative_height_bug.zip](https://github.com/thomasa88/ParametricText/files/6633550/negative_height_bug.zip)

**Comment by thomasa88** [comment]
It turns out that the Text1-Height parameter is negative:
![image](https://user-images.githubusercontent.com/89997/121575146-51369900-ca27-11eb-80c3-99ba5d9ee587.png)

The value should be 8 mm!

The text height workaround triggers this error when trying to write back the height after testing for presence of the bug. The same would happen if it tried to restore the height of a modified text:
```
ParametricText v 2.2.0-beta.1 error: 3 : invalid input height

Copy this message by taking a screenshot. Describe what you did to get this error or record a video.

--------------------------------------------------

Fusion 360 v. 2.0.10253
H:\my_src\fusion360\ParametricText\thomasa88lib\events.py failed: 

Traceback (most recent call last):
  File "H:/my_src/fusion360/ParametricText\thomasa88lib\events.py", line 142, in catcher
    func(args)
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 1352, in update_cmd_execute_handler
    update_texts(*async_update_queue_.get())
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 1312, in update_texts
    text_updated = set_sketch_text(sketch_text, evaluate_text(text, sketch_text, next_version))
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 717, in set_sketch_text
    sketch_text.text = text
  File "/packages\adsk\fusion.py", line 62798, in _set_text
    return _fusion.SketchText__set_text(self, value)
RuntimeError: 3 : invalid input height
```


**Workaround:** Edit the sketch text manually to correct the parameter. Nothing needs to be done. Just Edit the text, confirm that the height is correct and press Ok.
