### ISSUE TITLE
Parametric Text error

### ISSUE THREAD

**Issue by jpr73350** [thomasa88/ParametricText#51]
Hello,
I am getting the following error message when I use the change parameters option in fusion 360,
When I click on OK, on parameters i get this message:
I have installed from the autodesk fusion 360 app store plugin:
"ParametricText"
Message
Fusion 360
Copy this message using Ctrl+C:
C:\Users\jean-\AppData\Roaming\Autodesk\ApplicationPlugins\DirectName.bundle\Contents\thomasa88lib\events.py failed:
Traceback (most recent call last):
  File "C:\Users/jean-/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents\thomasa88lib\events.py", line 142, in catcher
    func(args)
  File "C:/Users/jean-/AppData/Roaming/Autodesk/ApplicationPlugins/DirectName.bundle/Contents/DirectName.py", line 350, in rename_command_destroy_handler
    ui_.activeSelections.clear()
  File "C:\Users/jean-/AppData/Local/Autodesk/webdeploy/production/df098dc22bdb0532c3884db0a2d6182c8f8678de/Api/Python/packages\adsk\core.py", line 15655, in clear
    return _core.Selections_clear(self)
RuntimeError: 2 : InternalValidationError : selecCmd
OK 
Best regards

**Comment by jpr73350** [comment]
Sorry Thomas I post at the wrong place
This concerns the DirectName add-in

**Comment by thomasa88** [comment]
No problem!

Correct issue is here: https://github.com/thomasa88/DirectName/issues/5
