### ISSUE TITLE
Failing Compute All is not handled

### ISSUE THREAD

**Issue by thomasa88** [thomasa88/ParametricText#9]
Need to handle compute all failing, due to e.g. lost references.

Example error

```
---------------------------
Fusion 360
---------------------------
ParametricText v 2.0.0 error: 5 : Sprue profile / Project1 // 1 Reference Failures The project source is lost, Cache is used! /// Edge 1 missing
Print bridge support / 1 Reference Failures The model is using cached geometry to solve. Please reselect reference geometry for failed features in the timeline. // Face 1 missing / 1 Reference Failures The profile reference is lost, try editing this the feature to reselect the lost profile. // Profile 1 missing
Clamp profile / Project3 // 1 Reference Failures The project source is lost, Cache is used! /// Face 1 missing
Split / Compute Failed // No intersection between target(s) and split tool.
Mold top version / Project1 // 1 Reference Failures The project source is lost, Cache is used! /// Face 1 missing
ImplicitJointOrigin4(Mold top print orientation) / 1 Reference Failures The body reference is lost, try editing this feature to reselect the lost body. // Body 1 missing / 2 Reference Failures The model is using cached geometry to solve. Please reselect reference geometry for failed features in the timeline. // Face 1 missing // Face 2 missing
ImplicitJointOrigin4(Mold bottom print orientation) / 1 Reference Failures The body reference is lost, try editing this feature to reselect the lost body. // Body 1 missing

Copy this message using Ctrl+C (Windows) or take a screenshot (Mac). Describe what you did to get this error or record a video.

--------------------------------------------------

H:\my_src\fusion360\ParametricText\thomasa88lib\events.py failed: 

Traceback (most recent call last):
  File "H:/my_src/fusion360/ParametricText\thomasa88lib\events.py", line 142, in catcher
    func(args)
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 1042, in document_saving_handler
    update_texts(text_filter=['_.version', '_.date'], next_version=True)
  File "H:/my_src/fusion360/ParametricText/ParametricText.py", line 1088, in update_texts
    design.computeAll()
  File "/packages\adsk\fusion.py", line 14688, in computeAll
    return _fusion.Design_computeAll(self)
RuntimeError: 5 : Sprue profile / Project1 // 1 Reference Failures The project source is lost, Cache is used! /// Edge 1 missing
Print bridge support / 1 Reference Failures The model is using cached geometry to solve. Please reselect reference geometry for failed features in the timeline. // Face 1 missing / 1 Reference Failures The profile reference is lost, try editing this the feature to reselect the lost profile. // Profile 1 missing
Clamp profile / Project3 // 1 Reference Failures The project source is lost, Cache is used! /// Face 1 missing
Split / Compute Failed // No intersection between target(s) and split tool.
Mold top version / Project1 // 1 Reference Failures The project source is lost, Cache is used! /// Face 1 missing
ImplicitJointOrigin4(Mold top print orientation) / 1 Reference Failures The body reference is lost, try editing this feature to reselect the lost body. // Body 1 missing / 2 Reference Failures The model is using cached geometry to solve. Please reselect reference geometry for failed features in the timeline. // Face 1 missing // Face 2 missing
ImplicitJointOrigin4(Mold bottom print orientation) / 1 Reference Failures The body reference is lost, try editing this feature to reselect the lost body. // Body 1 missing

---------------------------
OK   
---------------------------

```

**Comment by thomasa88** [comment]
The add-in can probably just ignore the error, but can we show an error "toast" message to the user?

**Comment by thomasa88** [comment]
Compute all error will show up as this:

![image](https://user-images.githubusercontent.com/89997/120891336-58fdd400-c608-11eb-9d1a-557826565274.png)

Tooltip:
![image](https://user-images.githubusercontent.com/89997/120891350-77fc6600-c608-11eb-944d-7082bb796815.png)

More info:
![image](https://user-images.githubusercontent.com/89997/120891368-96faf800-c608-11eb-8227-75edc7ca9a45.png)
